var searchData=
[
  ['usb_5fbsp',['USB_BSP',['../group__USB__BSP.html',1,'']]],
  ['usb_5fbsp_5fprivate_5fdefines',['USB_BSP_Private_Defines',['../group__USB__BSP__Private__Defines.html',1,'']]],
  ['usb_5fbsp_5fprivate_5ffunctions',['USB_BSP_Private_Functions',['../group__USB__BSP__Private__Functions.html',1,'']]],
  ['usb_5fbsp_5fprivate_5fmacros',['USB_BSP_Private_Macros',['../group__USB__BSP__Private__Macros.html',1,'']]],
  ['usb_5fbsp_5fprivate_5ftypesdefinitions',['USB_BSP_Private_TypesDefinitions',['../group__USB__BSP__Private__TypesDefinitions.html',1,'']]],
  ['usb_5fconf',['USB_CONF',['../group__USB__CONF.html',1,'']]],
  ['usb_5fconf_2eh',['usb_conf.h',['../usb__conf_8h.html',1,'']]],
  ['usb_5fconf_5fexported_5fdefines',['USB_CONF_Exported_Defines',['../group__USB__CONF__Exported__Defines.html',1,'']]],
  ['usb_5fconf_5fexported_5ffunctionsprototype',['USB_CONF_Exported_FunctionsPrototype',['../group__USB__CONF__Exported__FunctionsPrototype.html',1,'']]],
  ['usb_5fconf_5fexported_5fmacros',['USB_CONF_Exported_Macros',['../group__USB__CONF__Exported__Macros.html',1,'']]],
  ['usb_5fconf_5fexported_5ftypes',['USB_CONF_Exported_Types',['../group__USB__CONF__Exported__Types.html',1,'']]],
  ['usb_5fconf_5fexported_5fvariables',['USB_CONF_Exported_Variables',['../group__USB__CONF__Exported__Variables.html',1,'']]],
  ['usb_5fdesc',['USB_DESC',['../group__USB__DESC.html',1,'']]],
  ['usb_5fdesc_5fexported_5fdefines',['USB_DESC_Exported_Defines',['../group__USB__DESC__Exported__Defines.html',1,'']]],
  ['usb_5fotg_5fbsp_5fconfigvbus',['USB_OTG_BSP_ConfigVBUS',['../group__USB__BSP__Private__Functions.html#ga02dee21bb9a092415782c0e1a460981c',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5fdrivevbus',['USB_OTG_BSP_DriveVBUS',['../group__USB__BSP__Private__Functions.html#ga1a0b196001899cd61bc722d080ca8161',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5fenableinterrupt',['USB_OTG_BSP_EnableInterrupt',['../group__USB__BSP__Private__Functions.html#ga38bdd94d09d00f27d1343fdb0babdfa1',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5finit',['USB_OTG_BSP_Init',['../group__USB__BSP__Private__Functions.html#gacffb89e4346b11dee704fe5a40326a1f',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5fmdelay',['USB_OTG_BSP_mDelay',['../group__USB__BSP__Private__Functions.html#ga28c906bec05a1b7f91aa0e4ff5d8a16c',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5ftimeinit',['USB_OTG_BSP_TimeInit',['../group__USB__BSP__Private__Functions.html#ga880a11758cfe2348112a30a0ea44c32f',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5ftimerirq',['USB_OTG_BSP_TimerIRQ',['../group__USB__BSP__Private__Functions.html#ga97a8f22d2dce112b90488d9afd3fbbdb',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fbsp_5fudelay',['USB_OTG_BSP_uDelay',['../group__USB__BSP__Private__Functions.html#gaa70213d9a7b9b047dc6d3357f99e19b5',1,'deca_usb_bsp_evk1000.c']]],
  ['usb_5fotg_5fdriver',['USB_OTG_DRIVER',['../group__USB__OTG__DRIVER.html',1,'']]],
  ['usb_5fprintconfig',['usb_printconfig',['../group__USB__VCP__Private__Variables.html#gaf2622d49bb9b422ba14489aae673e1dc',1,'usb_printconfig(int, uint8 *, int):&#160;deca_usb.c'],['../group__USB__VCP__Private__Variables.html#gaf2622d49bb9b422ba14489aae673e1dc',1,'usb_printconfig(int size, uint8 *string, int s1switch):&#160;deca_usb.c']]],
  ['usb_5fstring_5fdescriptors',['USB_String_Descriptors',['../group__USB__String__Descriptors.html',1,'']]],
  ['usb_5fvcp_5fclass_5flayer_5fparameter',['USB_VCP_Class_Layer_Parameter',['../group__USB__VCP__Class__Layer__Parameter.html',1,'']]],
  ['usb_5fvcp_5fprivate_5fvariables',['USB_VCP_Private_Variables',['../group__USB__VCP__Private__Variables.html',1,'']]],
  ['usbd_5fdesc',['USBD_DESC',['../group__USBD__DESC.html',1,'']]],
  ['usbd_5fdesc_2ec',['usbd_desc.c',['../usbd__desc_8c.html',1,'']]],
  ['usbd_5fdesc_2eh',['usbd_desc.h',['../usbd__desc_8h.html',1,'']]],
  ['usbd_5fdesc_5fexported_5ffunctionsprototype',['USBD_DESC_Exported_FunctionsPrototype',['../group__USBD__DESC__Exported__FunctionsPrototype.html',1,'']]],
  ['usbd_5fdesc_5fexported_5fmacros',['USBD_DESC_Exported_Macros',['../group__USBD__DESC__Exported__Macros.html',1,'']]],
  ['usbd_5fdesc_5fexported_5ftypesdefinitions',['USBD_DESC_Exported_TypesDefinitions',['../group__USBD__DESC__Exported__TypesDefinitions.html',1,'']]],
  ['usbd_5fdesc_5fexported_5fvariables',['USBD_DESC_Exported_Variables',['../group__USBD__DESC__Exported__Variables.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5fdefines',['USBD_DESC_Private_Defines',['../group__USBD__DESC__Private__Defines.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5ffunctionprototypes',['USBD_DESC_Private_FunctionPrototypes',['../group__USBD__DESC__Private__FunctionPrototypes.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5ffunctions',['USBD_DESC_Private_Functions',['../group__USBD__DESC__Private__Functions.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5fmacros',['USBD_DESC_Private_Macros',['../group__USBD__DESC__Private__Macros.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5ftypesdefinitions',['USBD_DESC_Private_TypesDefinitions',['../group__USBD__DESC__Private__TypesDefinitions.html',1,'']]],
  ['usbd_5fdesc_5fprivate_5fvariables',['USBD_DESC_Private_Variables',['../group__USBD__DESC__Private__Variables.html',1,'']]],
  ['usbd_5fusr',['USBD_USR',['../group__USBD__USR.html',1,'']]],
  ['usbd_5fusr_2ec',['usbd_usr.c',['../usbd__usr_8c.html',1,'']]],
  ['usbd_5fusr_5fconfigstrdescriptor',['USBD_USR_ConfigStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#ga1a95bda8d761cd993c82234e043270fc',1,'USBD_USR_ConfigStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#ga1a95bda8d761cd993c82234e043270fc',1,'USBD_USR_ConfigStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5fdeviceconfigured',['USBD_USR_DeviceConfigured',['../group__USBD__USR__Private__Functions.html#ga8fad6d5efb792b500cfd1f5d0c970351',1,'usbd_usr.c']]],
  ['usbd_5fusr_5fdeviceconnected',['USBD_USR_DeviceConnected',['../group__USBD__USR__Private__Functions.html#gac680d8462dc3339d7f5a84378957cfd2',1,'usbd_usr.c']]],
  ['usbd_5fusr_5fdevicedescriptor',['USBD_USR_DeviceDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#gadd5d311559f5cf53f393f9b863bd8aae',1,'USBD_USR_DeviceDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#gadd5d311559f5cf53f393f9b863bd8aae',1,'USBD_USR_DeviceDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5fdevicedisconnected',['USBD_USR_DeviceDisconnected',['../group__USBD__USR__Private__Functions.html#gaea31856943d8abb8205004028cc817bd',1,'usbd_usr.c']]],
  ['usbd_5fusr_5fdevicereset',['USBD_USR_DeviceReset',['../group__USBD__USR__Private__Functions.html#gac10ea223f86ed47e7619b25ab71ed83a',1,'usbd_usr.c']]],
  ['usbd_5fusr_5fdeviceresumed',['USBD_USR_DeviceResumed',['../group__USBD__USR__Private__Functions.html#ga811ae379ad06261ef3fdbd123cff427e',1,'usbd_usr.c']]],
  ['usbd_5fusr_5fdevicesuspended',['USBD_USR_DeviceSuspended',['../group__USBD__USR__Private__Functions.html#ga62204dce5d51990ef90d52f0c8efc9a7',1,'usbd_usr.c']]],
  ['usbd_5fusr_5finit',['USBD_USR_Init',['../group__USBD__USR__Private__Functions.html#ga439704d4d2254602e672f6ce0528e3eb',1,'usbd_usr.c']]],
  ['usbd_5fusr_5finterfacestrdescriptor',['USBD_USR_InterfaceStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#gaf7003c494f598dd781416da3e468e615',1,'USBD_USR_InterfaceStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#gaf7003c494f598dd781416da3e468e615',1,'USBD_USR_InterfaceStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5flangidstrdescriptor',['USBD_USR_LangIDStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#gab5247caa36187728a45c43078d96497e',1,'USBD_USR_LangIDStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#gab5247caa36187728a45c43078d96497e',1,'USBD_USR_LangIDStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5fmanufacturerstrdescriptor',['USBD_USR_ManufacturerStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#gaeb4b6e96436cb53ade2b8276568c27d1',1,'USBD_USR_ManufacturerStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#gaeb4b6e96436cb53ade2b8276568c27d1',1,'USBD_USR_ManufacturerStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5fprivate_5fconstants',['USBD_USR_Private_Constants',['../group__USBD__USR__Private__Constants.html',1,'']]],
  ['usbd_5fusr_5fprivate_5fdefines',['USBD_USR_Private_Defines',['../group__USBD__USR__Private__Defines.html',1,'']]],
  ['usbd_5fusr_5fprivate_5ffunctionprototypes',['USBD_USR_Private_FunctionPrototypes',['../group__USBD__USR__Private__FunctionPrototypes.html',1,'']]],
  ['usbd_5fusr_5fprivate_5ffunctions',['USBD_USR_Private_Functions',['../group__USBD__USR__Private__Functions.html',1,'']]],
  ['usbd_5fusr_5fprivate_5fmacros',['USBD_USR_Private_Macros',['../group__USBD__USR__Private__Macros.html',1,'']]],
  ['usbd_5fusr_5fprivate_5ftypesdefinitions',['USBD_USR_Private_TypesDefinitions',['../group__USBD__USR__Private__TypesDefinitions.html',1,'']]],
  ['usbd_5fusr_5fprivate_5fvariables',['USBD_USR_Private_Variables',['../group__USBD__USR__Private__Variables.html',1,'']]],
  ['usbd_5fusr_5fproductstrdescriptor',['USBD_USR_ProductStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#ga3e9f418a2337898da999ca7548c414a9',1,'USBD_USR_ProductStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#ga3e9f418a2337898da999ca7548c414a9',1,'USBD_USR_ProductStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbd_5fusr_5fserialstrdescriptor',['USBD_USR_SerialStrDescriptor',['../group__USBD__DESC__Exported__FunctionsPrototype.html#ga61caa6dd47de36f32d25e2d6980e5904',1,'USBD_USR_SerialStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c'],['../group__USBD__DESC__Private__Functions.html#ga61caa6dd47de36f32d25e2d6980e5904',1,'USBD_USR_SerialStrDescriptor(uint8_t speed, uint16_t *length):&#160;usbd_desc.c']]],
  ['usbh_5fbsp_5fprivate_5ffunctionprototypes',['USBH_BSP_Private_FunctionPrototypes',['../group__USBH__BSP__Private__FunctionPrototypes.html',1,'']]],
  ['usbh_5fbsp_5fprivate_5fvariables',['USBH_BSP_Private_Variables',['../group__USBH__BSP__Private__Variables.html',1,'']]],
  ['usr_5fsfd_5fid',['USR_SFD_ID',['../deca__regs_8h.html#ae565af3d75091a4594000082f94972d8',1,'deca_regs.h']]]
];
